### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [zherczeg/sljit#10]
I would like to point out that an identifier like “[`_SLJIT_LIR_H_`](https://github.com/zherczeg/sljit/blob/54bdffab5fe00d8efe16ef928b9b7e2fa2348150/sljit_src/sljitLir.h#L27 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by zherczeg** [comment]
What is the expectation?

**Comment by elfring** [comment]
The affected include guards can become more standard compliant just by [the omission of a leading underscore](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").

**Comment by zherczeg** [comment]
Fixed in #83

**Comment by elfring** [comment]
Thanks for your adjustment of affected include guards.
