### ISSUE TITLE
How to enter JITed function at some instruction?

### ISSUE THREAD

**Issue by playXE** [zherczeg/sljit#104]
There's this statement in SL-JIT advantages: `The execution can be continued from any LIR instruction In other words, jump into and out of the code is safe.`. I finally started work on JS engine and I need to enter any point in the code for OSR (On Stack Replacement) when JITing hot loops, how I can do this with SL-JIT?

**Comment by zherczeg** [comment]
I don't know your use case, but you can get the phyisical address of each label by sljit_get_label_addr, and you can jump there with direct/indirect jumps. If the code pieces are generated in different times, they must have the same stack layout (called context). This can be ensured by sljit_set_context. This test generates various pieces of code blocks and connects them with jumps:

https://github.com/zherczeg/sljit/blob/master/test_src/sljitTest.c#L2983

**Comment by playXE** [comment]
I need to do OSR from interpreter to JITed code, interpreter is written in Rust and I don't have access to indirect goto's here. Here's pseudocode on how this OSR might look:
```rust
op_loophint => {
    let loop_info = loop_info[pc];
    if loop_info.threshold >= threshold {
       let code = jit_compile(frame.bytecode);
       let entry = code.code_map[pc];
       goto* entry; // <- this one is a problem, how do I go to `entry` addr?
    }
}


```

**Comment by zherczeg** [comment]
This will not work with indirect goto as well. That can only be used to jump inside a function even in gcc.

What you need to do is tail call to an sljit function, which sets up the stack, and pass it the real target adress, wher it jumps. So it is not a big deal, but you need to write a code where the compiler is smart enough to do a tail call optimization, even in debug mode.
