### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [zherczeg/sljit#11]
Would you like to add more error handling for return values from functions like the following?
- [fprintf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output") ⇒ [sljit_verbose_reg](https://github.com/zherczeg/sljit/blob/b01fcc0e130d28212b2317b37e5fe31c1a4760f0/sljit_src/sljitLir.c#L860)
- [pthread_mutex_lock](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html "Lock a mutex.") ⇒ [open_dev_zero](https://github.com/zherczeg/sljit/blob/78a9bf17b51d9f742d8314a30ca5e3382965c2e1/sljit_src/sljitUtils.c#L188)

**Comment by zherczeg** [comment]
I don't really understand your request. Do you want more error codes?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by zherczeg** [comment]
I will never check the return value of printf, but mutex lock can be, although it would be a libc bug if that function fails.

**Comment by elfring** [comment]
* Should file output failures get also any more development attention in addition to data synchronisation difficulties?
* How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
