### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by cohomology** [zherczeg/sljit#128]
Hi Zoltan,

could you just add "some" LICENSE to your github repository?

We formerly use PCRE2 in our commercial product but now want to use SLJIT independently of it. I BSD 3 clause license would be good  ...

I know that the source files contain some bsd 3 clause license, but a separate LICENSE file would make the process easier for law departments of large companies :-).

Thanks,
Kilian

**Comment by zherczeg** [comment]
I have added a license file:
https://github.com/zherczeg/sljit/blob/master/LICENSE

Thank you for using the library.
