### ISSUE TITLE
How is sljit different from GNU Lightning?

### ISSUE THREAD

**Issue by nordlow** [zherczeg/sljit#146]
Would be worthwhile having a comparison with GNU lightning.

**Comment by zherczeg** [comment]
I don't know much about them, so maybe somebody who knows both can do a better comparison. The license is definitely different. The project focus also seems different, they want to emulate a generic risc cpu, while sljit focuses to be a common denominator of cpu features.

**Comment by nordlow** [comment]
Ok, thanks.

**Comment by zherczeg** [comment]
2 clause bsd.
https://opensource.org/licenses/BSD-2-Clause
Maybe the simplest ever.

**Comment by nordlow** [comment]
Ok, thanks.
