### ISSUE TITLE
Better API for SLJIT_FAST_CALL with 2 different compilers

### ISSUE THREAD

**Issue by cohomology** [zherczeg/sljit#167]
There are situations when you have 2 jitted functions A and B and you want to call B from A via SLJIT_FAST_CALL. For some reasons you can't create A and B at the same time. So at time T1 with compiler C1 you want to create A and some time later at time T2 with compiler C2 you want to create B. The address of B is transferred to A via an input parameter, for example.

The problem here is that you can't "elegantly" say the compiler C2 how many scratches and saveds you have. This is not "really" needed for SLJIT_FAST_CALL but all the checks in the sljit_emit_* commands test for the values being present. 

At the moment I workaround the problem by manually setting for example:
```
compiler->scratches = 6;
compiler->saveds = 6;
compiler->fscratches = 1;
```
before the SLJIT_FAST_ENTER call at time T2 for compiler C2.

Wouldn't it be possible to specify those when creating the compiler?

**Comment by zherczeg** [comment]
Have you tried this function: sljit_set_context
https://github.com/zherczeg/sljit/blob/master/sljit_src/sljitLir.h#L744

It allows to specify everything without generating any instructions.

**Comment by cohomology** [comment]
Thank you, Zoltan ... missed that function.
