### ISSUE TITLE
x86 CPUs without SSE4.1 no longer supported

### ISSUE THREAD

**Issue by carenas** [zherczeg/sljit#182]
Athlon II X4 640 running 32bit Linux which throws SIGILL for all tests above 94 and after SSE4.1 detection was finally fixed with #181.

Also affecting Intel(R) Xeon(TM) CPU 3.20GHz running 64bit Linux

**Comment by zherczeg** [comment]
The plan is that sse4.1 only needed for simd.  All simd functions could return with sljit_unsupported if SSE4.1 is not present.

**Comment by zherczeg** [comment]
I am sorry, I haven't noticed your PR. I have landed a commit which is quite similar to your proposal: be7b02a41a6ae9fbb8e12c454d8ea9543652faad

It is not fine grained enough, but should improve the current situation.

**Comment by carenas** [comment]
Impressive; there is also a related problem with ARM which will be better tracked independently
