### ISSUE TITLE
Reclaiming unused space in executable allocations

### ISSUE THREAD

**Issue by invertego** [zherczeg/sljit#207]
I understand that `sljit_generate_code` can allocate executable memory in excess of the necessary amount, as the exact amount of required space is not known at the start of the call. That said, I can see no way to cleanly reclaim the unused space at the end of every allocation.

I have a custom executable allocator, and currently I can use `sljit_get_generated_code_size` to determine the actual amount of used memory... on most architectures. However, on PPC (when SLJIT_INDIRECT_CALL=1) and s390x, there may be additional data at the end. It makes me feel that I probably shouldn't be using this API in that way.

I see a few ways forward:
1) A new getter API that includes total amount of used space, including any data after the executable code
2) A new SLJIT_REALLOC_EXEC [1] macro invoked at the end of the generate function to signal the reduced size to the allocator; the default implementation could do nothing, as it would only be used to shrink allocations.
3) Live life and stop worrying about a few unused bytes

I'm curious if there is any preference here, or if I've overlooked another possible solution.

[1] Maybe a bad name, because unlike `realloc` it should never move things around

**Comment by carenas** [comment]
> I've overlooked another possible solution

provide another customizable allocator that will be called when additional memory for data is needed and therefore you could always trust that `sljit_get_generated_code_size` is always accurate.

I wonder though, why isn't option 3 the most obvious choice?, how much space (as a % of the generated code, and including any alignment needs) are you expecting to save?

**Comment by invertego** [comment]
> I wonder though, why isn't option 3 the most obvious choice?, how much space (as a % of the generated code, and including any alignment needs) are you expecting to save?

I just took some measurements, and for [our use case](https://github.com/ares-emulator/ares), on x86_64, we're seeing ~20%-40% wasted space. We generate branch-heavy code and the extreme pessimization of direct branch size estimates (13 bytes!) seems to be the killer.

> provide another customizable allocator that will be called when additional memory for data is needed and therefore you could always trust that `sljit_get_generated_code_size` is always accurate.

That could work, but I'm having a hard time seeing how one could implement such an API while still making it easy for the data to be placed immediately after the executable code as it is today.

**Comment by zherczeg** [comment]
I think this is a valid use case. It is true that branches are overestimated, and you cannot reallocate code, since the absolute offsets embedded into the code would become invalid. The estimation could be improved as well.

https://github.com/zherczeg/sljit/blob/master/sljit_src/sljitNativeX86_common.c#L790
https://github.com/zherczeg/sljit/blob/master/sljit_src/sljitNativePPC_common.c#L667C77-L667C77

We could add a macro, which is defined as nothing by default, or add everything to `executable_size`.

**Comment by zherczeg** [comment]
@invertego a patch is proposed to improve `sljit_get_generated_code_size`, which can be used after the code is created to get the real size of the used memory. Would this be enough for you, or do you want something else?

**Comment by invertego** [comment]
That would work for me. I imagine some might be interested in identifying the code/data split (e.g. to disassemble just the code portion for debugging purposes) but that's not a particular concern of mine, at least for the platforms I care most about.

**Comment by carenas** [comment]
> That would work for me

Note that for PPC with SLJIT_INDIRECT_CALL=1 (which is hopefully not that common in practice) it will still be a little awkward to use, because the pointer address you get from `sljit_generate_code` points to the trampoline at the end of the generated code.
