### ISSUE TITLE
What's the difference between emit_put_label and emit_label?

### ISSUE THREAD

**Issue by stevefan1999-personal** [zherczeg/sljit#230]
I read the source code and documents and I'm still confused why do we need emit_put_label instead of just emit_label.

**Comment by zherczeg** [comment]
The `sljit_emit_label` adds a label to the instruction stream, and you can use it as a jump target or label for `sljit_set_put_label`. The `emit_put_label` copies the target address of a label to a destination operand. This address can be used for various purposes, such as a target for indirect jumps. Basically it copies a constant value to a destination, but the constant is not known before the executable code is generated with `sljit_generate_code`. This is not the only way to do this, but on some systems (e.g. RiscV) this method is better than any other way.
