### ISSUE TITLE
Update loongarch

### ISSUE THREAD

**Issue by zherczeg** [zherczeg/sljit#232]
@lrzlin some updates are needed in the loongarch code after the recent changes. There is a new serializer interface, and `label->addr` needs to be changed to `label->u.addr`.

This update is not necessary, but recommended. Many platforms has a `reduce_code_size` function now:
https://github.com/zherczeg/sljit/blob/master/sljit_src/sljitNativeRISCV_common.c#L405

This function tries to reduce the space allocated for branches, which improves branch construction and reduces code size. On the regex benchmark the code size reduction is around 30-50% on 64 bit, and 20-40% on 32 bit cpus, so this is quite significant saving.

**Comment by lrzlin** [comment]
OK, I'll working on it as soon as possible, thanks for remind me that.

**Comment by zherczeg** [comment]
@lrzlin I have added a few macros to specify how the upper 32 bit is used by 32 bit operations on 64 bit:
https://github.com/zherczeg/sljit/blob/master/sljit_src/sljitConfigInternal.h#L53

Could you update LoongArch? Should be a minor thing. Thank you!
