### ISSUE TITLE
Add comparison of sljit to its alternatives

### ISSUE THREAD

**Issue by nordlow** [zherczeg/sljit#241]
It would be useful to have a short overview of the pros and cons of sljit compared to alternatives such as GNU lightning, libgccjit, etc.

**Comment by zherczeg** [comment]
How others do this comparison? Do you have an example?

**Comment by nordlow** [comment]
> How others do this comparison? Do you have an example?

I haven't found one yet.

However, there are lots of discussion on various forums such as

https://www.reddit.com/r/ProgrammingLanguages/comments/jhaand/what_code_generators_are_there/

.

**Comment by zherczeg** [comment]
It seems this could be an apple vs oranges comparison. Each compiler targets a different use case, and they are tailored for that purpose. This defines their strengths and weaknesses. Sljit is a very low-level platform independent compiler, where you need to do all the optimizations. It offers a wide range of operations, not just the usual C operators. GNU lightning seems somewhat similar, but it also brings the GNU license. The others are not really.
