### ISSUE TITLE
Undefined Behavior in sljitTest.c

### ISSUE THREAD

**Issue by krytarowski** [zherczeg/sljit#25]
`UBSan: Undefined Behavior in /usr/src/sys/external/bsd/sljit/dist/test_src/sljitTest.c:568:113, left shift of 1 by 63 places cannot be represented in type 'sljit_sw' (aka 'long')`

**Comment by krytarowski** [comment]
Another one:

`UBSan: Undefined Behavior in /usr/src/sys/external/bsd/sljit/dist/test_src/sljitTest.c:585:73, left shift of 1 by 63 places cannot be represented in type 'long long'`

Reported on NetBSD with MKLIBCSANITIZER.

**Comment by zherczeg** [comment]
Those lines does not contain any shift. Could you give me those lines in the latest master? What is the right way to do this which is compatible with all C compilers?

**Comment by krytarowski** [comment]
` sljit_emit_op1(compiler, SLJIT_NEG | SLJIT_SET_Z | SLJIT_SET_OVERFLOW, SLJIT_UNUSED, 0, SLJIT_IMM, (sljit_sw)1 << ((sizeof(sljit_sw) << 3) - 1));`

` sljit_emit_op1(compiler, SLJIT_MOV, SLJIT_R0, 0, SLJIT_IMM, SLJIT_W(1) << ((sizeof(sljit_sw) << 3) - 1));
`

`sljit_sw` is a signed 64bit integer. Does it make sense to change its signedness bit? If so, please go for `(sljit_sw)1` -> `1ULL`.

**Comment by krytarowski** [comment]
Ping?

Maybe just remove these patches and avoid fiddling with the signedness bit?

**Comment by zherczeg** [comment]
I am sorry.
I fixed it, please check if it works for you.
https://github.com/zherczeg/sljit/commit/4c741e240668ab4cc4fdb67b67d8a566f98e07bf

**Comment by carenas** [comment]
> Those lines does not contain any shift. Could you give me those lines in the latest master? What is the right way to do this which is compatible with all C compilers?

CFLAGS="-fsanitize=undefined" make
bin/sljit_test

**Comment by krytarowski** [comment]
Fixed!
