### ISSUE TITLE
Breakpoint opcode encoding on ARM64

### ISSUE THREAD

**Issue by invertego** [zherczeg/sljit#266]
sljit currently implements the breakpoint opcode with `brk #0` on ARM64. The Windows kernel treats `brk` instructions differently depending on the immediate field. For `#0` it produces an illegal instruction exception. To produce a breakpoint exception (like `int3` does on x86) requires an immediate of `#0xf000`. With a debugger attached, you can also resume execution at the next instruction after a breakpoint exception (unlike illegal instruction exceptions).

LLVM 9 changed the implementation of its `debugtrap` intrinsic, exposed from clang as `__builtin_debugtrap()` and also as `__debugbreak()` (for compatibility with MSVC), to emit `brk #0xf000` for ARM64 Windows targets. In LLVM 12 this change was extended to all other ARM64 targets (for which it used to emit `brk #1`).

For sljit, I think it would be preferable for the breakpoint opcode be implemented with `brk #0xf000` on Windows. It would also be an option to follow LLVM's lead and make the change for all target OSes.

I could open a PR for either change, but I wanted to gauge reactions first.

References:
https://learn.microsoft.com/en-us/cpp/intrinsics/debugbreak?view=msvc-170
https://devblogs.microsoft.com/oldnewthing/20220822-00/?p=107032
https://reviews.llvm.org/D63635
https://reviews.llvm.org/D84014

**Comment by carenas** [comment]
following LLVM (redefining BRK to 0xd43e0000) seems sensible, and will indeed fix a bug in macOS arm64 as well where the attached debugger wouldn't let you continue unless $PC was set past the BRK instruction.

**Comment by zherczeg** [comment]
I was not aware of any limitations of breakpoint instructions. Feel free to change it to any value.

**Comment by invertego** [comment]
Indeed, it appears that `brk #0xf000` also gets special treatment from lldb on macOS in addition to Windows:
https://reviews.llvm.org/D91238
https://reviews.llvm.org/D109777

On Ubuntu Linux, no encoding seems to get special treatment under gdb or lldb. gdb used to have difficulty with encodings other than `brk #0`, but this was fixed in 2020 for the release of gdb 10:
https://github.com/bminor/binutils-gdb/commit/5133a31537c8f90f3b8b7172f385b3b2856d1566
