### ISSUE TITLE
Spurious assert on x86_64

### ISSUE THREAD

**Issue by invertego** [zherczeg/sljit#272]
When generating x86_64 code for a function that contains a mix of branches to a label and to a target address, the following assert may fire spuriously:

```
Assertion failed at sljit_src/sljitNativeX86_common.c:955
SLJIT_ASSERT((sljit_uw)code_ptr - addr <= ((jump->flags >> JUMP_SIZE_SHIFT) & 0x1f));
```

Here's a self-contained repro:
```
void repro(void)
{
	struct sljit_compiler* compiler;
	struct sljit_jump* jump;
	struct sljit_label* label;
	void* nullsub;
	void* code;

	// emit function that simply returns
	compiler = sljit_create_compiler(NULL);
	sljit_compiler_verbose(compiler, stdout);
	sljit_emit_enter(compiler, 0, SLJIT_ARGS0V(), 0, 0, 0);
	sljit_emit_return_void(compiler);
	nullsub = sljit_generate_code(compiler, 0, NULL);
	sljit_free_compiler(compiler);

	// emit function that calls nullsub
	compiler = sljit_create_compiler(NULL);
	sljit_compiler_verbose(compiler, stdout);
	sljit_emit_enter(compiler, 0, SLJIT_ARGS0V(), 0, 0, 0);

	// emit many calls to nullsub
	for (int i = 0; i < 16; i++)
		sljit_emit_icall(compiler, SLJIT_CALL, SLJIT_ARGS0V(), SLJIT_IMM, SLJIT_FUNC_ADDR(nullsub));

	// emit jump to next instruction (return)
	jump = sljit_emit_jump(compiler, SLJIT_JUMP);
	label = sljit_emit_label(compiler);
	sljit_set_label(jump, label);	
	sljit_emit_return_void(compiler);

	// assert fires here
	code = sljit_generate_code(compiler, 0, NULL);
	sljit_free_compiler(compiler);

	sljit_free_code(nullsub, NULL);
	sljit_free_code(code, NULL);
}
```

From a quick look at the implementation, this seems to be the result of `detect_near_jump_type()` using `label->size` when calculating the branch distance. For a forward branch, this value will still be just an estimate produced by `reduce_code_size()`. With many preceding branches to a target address, this value could be a large overestimate if the actual size of those branches is much less than `JUMP_MAX_SIZE`. As a result, the distance between the actual source address and estimated label address can be larger than the branch distance estimated by `reduce_code_size()`.

**Comment by zherczeg** [comment]
I did this code a long time ago. At first glance, the estimate is correct, since "emit jump to next instruction (return)" is a very short distance jump. However, the distance is calculated using the current physical address for forward jumps, instead of their estimated address, and these two can have a large difference.

I see these cases:
1) Backward jump and absolute label address: "absolute jump address" - "absolute label address"
2) Forward jump: "estimated label address" - "estimated jump address"

**Comment by zherczeg** [comment]
Thank you for reporting this issue. It caused issues on a few cpus, but also a missing optimization opportunity on many others. The patch is landed here: 666125ad64fc694aafe6b816822ab446db14f5fe

@lrzlin maybe it is worth to port the changes to loongarch even if the new test is working. Optimizations are useful.

**Comment by invertego** [comment]
Thank you for the quick fix. I did some testing on that commit and I'm no longer seeing asserts fire in debug builds of our application. I can also see that smaller branch encodings are being used in some cases.

**Comment by zherczeg** [comment]
Great! Let me know if you need more features in the compiler, I will think about them.
