### ISSUE TITLE
Can't build with sljit on ubuntu x64

### ISSUE THREAD

**Issue by nmodnation** [zherczeg/sljit#43]
gcc -Wall -O3 -fcf-protection -DSLJIT_CONFIG_AUTO=1 -DSLJIT_UTIL_GLOBAL_LOCK=0 -DSLJIT_SINGLE_THREADED=1 -DSLJIT_DEBUG=0 -DSLJIT_VERBOSE=0 -c -o src/bean.o src/bean.c
In file included from src/sljit/sljitLir.h:81,
                 from src/bean.h:5,
                 from src/bean.c:1:
src/sljit/sljitConfigInternal.h:219:2: error: #error "-mshstk is needed to compile with -fcf-protection"

uname -a
Linux mod-VirtualBox 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Thanks.

**Comment by zherczeg** [comment]
Sorry for the late answer. `-mshstk` is needed by gcc for whatever reason. Just pass it to the compiler.

**Comment by nmodnation** [comment]
Thanks!
