### ISSUE TITLE
bswap instruction

### ISSUE THREAD

**Issue by xR3b0rn** [zherczeg/sljit#48]
I want to discuss whether it is a good idea to introduce the BSWAP instruction.

The idea is to introduce a new macro `SLJIT_BSWAP_X` which emits the x86/x64 `bswap` instruction when `sljit_emit_op1(compiler, SLJIT_BSWAP, ...)` is called.
```C++
sljit_emit_enter(compiler, 0, SLJIT_ARG1(SW), 0, 0, 0, 0, 0);
// this code shall emit the bswap instruction
sljit_emit_op1(compiler, SLJIT_BSWAP_64, SLJIT_R0, 0, SLJIT_MEM1(SLJIT_S0), 0);
sljit_emit_return(compiler, SLJIT_MOV, SLJIT_R0, 1);
```

If the instruction is not exisiting on a specific platform the conventional way of byte swapping shall be emitted:
```C++
uint64_t val = 64; // memory to byteswap
val = ( (((val) >> 56) & 0x00000000000000FF) | (((val) >> 40) & 0x000000000000FF00) | \
   (((val) >> 24) & 0x0000000000FF0000) | (((val) >>  8) & 0x00000000FF000000) | \
   (((val) <<  8) & 0x000000FF00000000) | (((val) << 24) & 0x0000FF0000000000) | \
   (((val) << 40) & 0x00FF000000000000) | (((val) << 56) & 0xFF00000000000000) );
```

**Comment by zherczeg** [comment]
Sounds good. I think x86 is not the only cpu with such instruction. SLJIT_CLZ works a similar way.

**Comment by xR3b0rn** [comment]
Do you have some guidelines for contributions? And do you have a testing process what I can follow?
I am able to test x86, x64-code, other architectures are hard to test for me.

**Comment by xR3b0rn** [comment]
Do you have some guidelines for contributions? And do you have a testing process what one can follow?

**Comment by Limaaron** [comment]
i think bswap implementation would be a good idea not only for x86_64 architecture

> If the instruction is not exisiting on a specific platform the conventional way of byte swapping shall be emitted:
> 
> ```c++
> uint64_t val = 64; // memory to byteswap
> val = ( (((val) >> 56) & 0x00000000000000FF) | (((val) >> 40) & 0x000000000000FF00) | \
>    (((val) >> 24) & 0x0000000000FF0000) | (((val) >>  8) & 0x00000000FF000000) | \
>    (((val) <<  8) & 0x000000FF00000000) | (((val) << 24) & 0x0000FF0000000000) | \
>    (((val) << 40) & 0x00FF000000000000) | (((val) << 56) & 0xFF00000000000000) );
> ```

More efficient version:
```c++
#define BSWAP64( var ) \
    (var) = ( ( (var) << 8u  ) & 0xFF00FF00FF00FF00ull ) | ( ( (var) >> 8u  ) & 0x00FF00FF00FF00FFull );  \
    (var) = ( ( (var) << 16u ) & 0xFFFF0000FFFF0000ull ) | ( ( (var) >> 16u ) & 0x0000FFFF0000FFFFull );  \
    (var) = ( (var) << 32u ) | ( ( (var) >> 32u ) & 0xFFFFFFFFull )
```

**Comment by zherczeg** [comment]
I am aware of this. You can generate the next constant using xor operation. E.g:

`0xFFFFFFFFull ^ (0xFFFFFFFFull << 16) == 0x0000FFFF0000FFFFull`
`0x0000FFFF0000FFFFull ^ (0x0000FFFF0000FFFFull << 8) == 0x00FF00FF00FF00FFull`

And a single constant is enough in each step.

`c = 0x0000FFFF0000FFFFull` -> `((var & c) << 16) | ((var >> 16) & c)`

So you need 3 registers: value, const, tmp
```
const = 0xFFFFFFFFull
tmp = value  >> 32
value = value << 32
value |= tmp

tmp = const
const <<= 16
const ^= tmp

tmp = value >> 16
value = value << 16
value &= const
tmp &= const
vauel |= tmp

...
```

Still plenty of operation, but managable.

**Comment by zherczeg** [comment]
`SLJIT_REV` and `SLJIT_REV32` are implemented. Maybe a 16 bit version will be implemented later.
