### ISSUE TITLE
More than 3 arguments

### ISSUE THREAD

**Issue by fgmccabe** [zherczeg/sljit#49]
How is one supposed to handle a function that has more than 3 arguments? 
One would normally spill these on the stack; but the callee needs to access them.
Could you point me to the appropriate place to look?
Thanks

**Comment by zherczeg** [comment]
Currently sljit supports maximum of four arguments. They can be word, int32, single or double precision. Each ABI defines how these arguments are passed to the callee. Here are some examples:

- Some ABIs passes all data on stack, some uses registers for the first n arguments

- Some ABIs use the first n registers, others keep their argument position index.
Example: f(int a, double b, int c, double d)
ABI type1: a -> reg0, c -> reg1, b -> float_reg0, d -> float_reg1
ABI type 2: a -> reg0, b-> float_reg1, c -> reg2, d -> float_reg3

- Some ABIs squeze arguments into as little space as possible, others leave gaps.
Example: f(float a, double b, float c) // ecah passed on stack
ABI type 1: push a, push c, push b (required size 16 bytes)
ABI type 2, push a, skip 4 bytes, push b, push c, skip 4 bytes (required size 24 bytes)

If you want to find an ABI for the target, just search "ABI cput type" in google.
Linux, x86-32: https://01.org/sites/default/files/file_attach/intel386-psabi-1.0.pdf
Linux, x64: https://uclibc.org/docs/psABI-x86_64.pdf
Windows, x64: https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=vs-2019
ARM-32 : https://developer.arm.com/architectures/system-architectures/software-standards/abi
ARM-64: https://c9x.me/compile/bib/abi-arm64.pdf
PowerPC: https://refspecs.linuxfoundation.org/ELF/ppc64/PPC-elf64abi.html
etc.

It is a lot of work to support them all. To tell you the truth supporting any kind of arguments is beyond the scope of a lightweight jit. But if you prefer using stack, you can create stack space for your arguments, and pass the starting address of the argument space to the called function.
