### ISSUE TITLE
handle 64 bit values

### ISSUE THREAD

**Issue by xR3b0rn** [zherczeg/sljit#50]
I observed that this code:
```C++
sljit_compiler* compiler = sljit_create_compiler(NULL);
sljit_emit_enter(compiler, 0, SLJIT_ARG1(SW), 0, 0, 0, 0, 0);
sljit_emit_op1(compiler, SLJIT_MOV, SLJIT_R0, 0, SLJIT_MEM1(SLJIT_S0), 0);
sljit_emit_op2(compiler, SLJIT_LSHR, SLJIT_R0, 0, SLJIT_R0, 0, SLJIT_IMM, 32);
sljit_emit_op2(compiler, SLJIT_AND, SLJIT_R0, 0, SLJIT_R0, 0, SLJIT_IMM, 0x0F);
sljit_emit_return(compiler, SLJIT_MOV, SLJIT_R0, 1);
void* code = sljit_generate_code(compiler);
using func_t = sljit_sw (SLJIT_FUNC *)(uint64_t* a);
func_t cf = reinterpret_cast<func_t>(code);
uint64_t u64b = 0x0123456789ABCDEF;
sljit_sw result = cf(&u64b);
std::cout << result << std::endl;
```
gives different outputs when switching between compiling x64 and compiling x86. Imo. this should not be the case since this violates the platform independence.

Is there a way to handle 64 bit values in "maschine independent" style? What is the best practice?

**Comment by zherczeg** [comment]
32 bit cpus cannot do 64 bit operations. In general sljit (or rather most CPUs) can do 32 bit or machine word operations. These types are the same on 32 bit cpus. Some 64 bit operations are easy to emulate on 32 bit (e.g. addition with SLJIT_ADDC, subtraction with SLJIT_SUBC, immediate shifting) but in general you might need helper functions to do the work (e.g. 64 bit division is complicated, but even a 64 bit multiply requires 4 multiply long operations and several additions).

**Comment by xR3b0rn** [comment]
So "platform independent" in the manner of sljit is only relates to 32-bit operations? And any 64-bit operation is not platform independent and will end up in UB when it runs on 32-bit? Isn't the library platform dependent then?

But as I understand you, the right way would be using defines: Emitting 64 shifts on 64 bit maschines and some more instructions on 32 bit maschines to emulate 64 bit shift?

**Comment by zherczeg** [comment]
Sljit never defined any 64 bit operations. It always supported two types: machine word and 32 bit. Machine word can be 32 or 64 bit long depending on the CPU. Even if you use gcc, 64 bit operations on 32 bit systems are emulated and often very slow. Sljit is a low level library, but you can build any layers above it, such as basic block support. If you build a 64 bit compatibility layer on 32 bit, and share this library, I am sure others will be grateful.
