### ISSUE TITLE
Add support for a new allocator with RW <-> RX swapping

### ISSUE THREAD

**Issue by krytarowski** [zherczeg/sljit#56]
There are architectural issues with handing RWX and double mapping RW + RX in the NetBSD kernel.

The RWX one is not portable to userland implementations through rumpkernel and requires disabled PaX MPROTECT hardening.

The double concurrent mapping RW+RX of the same physical pages has a few issues with cache, internal MMU handling etc.

There is need for another allocator that uses mprotect() [in userland, with a direct equivalent in the kernel] to switch between RW and RX mappings. mprotect() does the right thing with MMU, icache etc.

**Comment by krytarowski** [comment]
CC: @carenas

**Comment by zherczeg** [comment]
The core problem with flipping RX to RW is what happens if two threads use the same page: one for executing code and another for writing instructions. One possible solution is creating a separate allocator, which allocates pages for each code block individually but this may waste a lot of memory.

**Comment by zherczeg** [comment]
Another question: if the OS has issues handling something valid, could it be fixed? Isn't this a security issue?

**Comment by carenas** [comment]
> One possible solution is creating a separate allocator, which allocates pages for each code block individually but this may waste a lot of memory.

and it would still fail in NetBSD if the process fork() and the code needs to be updated, until there is a fix for lib/55177 (probably what is referred as "internal MMU handling" above).

**Comment by carenas** [comment]
@krytarowski could you elaborate on the "issues with cache"?, there is an architecture/platform dependent SLJIT_CACHE_FLUSH() macro that should take care of it, and if it is not working will need fixing independently of what we can do to workaround the PaX MPROTECT issues raised here as the main issue.

the following program is what I used originally to test (independently of sljit), NetBSD's buggy mprotect/mremap workaround for PaX:

`
#include <sys/mman.h>
#include <sys/wait.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

const int size = 4096;

int main()
{
  char *maprw = mmap(NULL, size,
                        PROT_READ|PROT_WRITE|PROT_MPROTECT(PROT_EXEC),
                        MAP_ANON|MAP_PRIVATE, -1, 0);
  char *maprx = mremap(maprw, size, NULL, size, MAP_REMAPDUP);
  mprotect(maprx, size, PROT_READ|PROT_EXEC);

  strcpy(maprw, "parent");
  printf("%s = %s\n", maprw, maprx);

  if (fork()) {
    char *remap = mremap(maprw, size, NULL, size, MAP_REMAPDUP);
    printf("%s = %s = %s\n", maprw, maprx, remap);
    strcpy(maprw, "child");
    __builtin___clear_cache(maprw, (void *)((uintptr_t)maprw + size));
    printf("%s = %s != %s\n", maprw, maprx, remap);
    munmap(remap, size);
    munmap(maprx, size);
    munmap(maprw, size);
    _exit(0);
  }
  wait(NULL);

  char *remap = mremap(maprw, size, NULL, size, MAP_REMAPDUP);
  printf("%s = %s = %s\n", maprw, maprx, remap);
  strcpy(maprw, "secret");
  printf("%s != %s = %s\n", maprw, maprx, remap);

  munmap(remap, size);
  munmap(maprx, size);
  munmap(maprw, size);
  return 0;
}
`

**Comment by krytarowski** [comment]
I've proposed the following patch:

http://netbsd.org/~kamil/patch-00272-sljit-JIT.txt

But it was rejected and I was requested to change sljit to have RW <-> RX switch.

There were 3 issues pointed out:

 - required allocation the second mapping at a cache-compatible virtual address on VAC platforms
 - coordination between writting and executing, this needs additional pmap handling
 - if the pages are modified after executing, there is need to icache flush

Using a single mapping with an RW<->RX switch fixes all these issues.

Next, using the same logic in PaX MPROTECT userland with mprotect(2) is straightforward and we don't need to use mremap(2) at all.

**Comment by krytarowski** [comment]
> The core problem with flipping RX to RW is what happens if two threads use the same page: one for executing code and another for writing instructions.

Generally concurrent writing and executing is not reliable and swapping RW <-> RX handles this.

> One possible solution is creating a separate allocator, which allocates pages for each code block individually but this may waste a lot of memory.

The RW+RX allocator is also documented as wasting a lot of memory and I think this is overstatement.

> Another question: if the OS has issues handling something valid, could it be fixed? Isn't this a security issue?

RWX mappings are considered as insecure and forbidden in hardened scenarios. They happened to be also sensitive to issues with icache and similar properties of the hardware.

> and it would still fail in NetBSD if the process fork() and the code needs to be updated, until there is a fix for lib/55177 (probably what is referred as "internal MMU handling" above).

OK, this has to be fixed, but it is rather unrelated to RW <-> RX swapping allocator.

**Comment by carenas** [comment]
> I was requested to change sljit to have RW <-> RX switch.

Maybe we are not all understanding what you mean by "RW <-> RX switch", but doing

  code = mmap(PROT_READ|PROT_WRITE, MAP_ANON|MAP_PRIVATE);
  /* define and compile into *code */
  mprotect(code, PROT_READ|PROT_EXEC);

will be prevented to work by PaX MPROTECT and is the whole reason why mremap(MREMAP_DUP) was needed to begin with (but has a bug).

if you want to allow that, there is already a way: disable PaX MPROTECT (as was already being done AFAIK)

if you want instead a per thread way to flip permission flags (maybe even with hardware assist) then Apple's API for their next version of macOS (#51) might be worth looking at and that is likely to be supported soon by the main allocator.

**Comment by krytarowski** [comment]
```
Maybe we are not all understanding what you mean by "RW <-> RX switch", but doing

code = mmap(PROT_READ|PROT_WRITE, MAP_ANON|MAP_PRIVATE);
/* define and compile into *code */
mprotect(code, PROT_READ|PROT_EXEC);

will be prevented to work by PaX MPROTECT and is the whole reason why mremap(MREMAP_DUP) was needed to begin with (but has a bug).
```

You need to do:

```
code = mmap(PROT_READ|PROT_WRITE|PROT_MPROTECT(PROT_EXEC), MAP_ANON|MAP_PRIVATE);
```

and then you can mprotect(2) this RW<->RX with enforced PaX MPROTECT.

The kernel APIs have an equivalent call for userland mprotect(2).

**Comment by krytarowski** [comment]
@carenas this RW<->RX approach is already used in LLVM JIT and is compatible with PaX MPROTECT.

https://github.com/llvm/llvm-project/blob/9f69157bf4a083f539e6759ddd6929c1b3d0bc2a/llvm/lib/Support/Unix/Memory.inc#L110

**Comment by carenas** [comment]
this might even work if /carenas/sljit/tree/nullexec is anything other than revolting

**Comment by krytarowski** [comment]
@carenas does this code work?

I recommend to keep the mprotect(2) logic for all kernels. The only NetBSD's extension is to set `PROT_MPROTECT(PROT_EXEC)` in the initial mmap() call.

I recommends to reuse LLVM's idea to clear the cache for setting pages executable.

**Comment by carenas** [comment]
> @carenas does this code work?

there is even a version of it that applies[1] to PCRE

[1] https://bugs.exim.org/show_bug.cgi?id=2626

**Comment by krytarowski** [comment]
Great work! I'm looking forward to get it reviewed by upstream.

**Comment by carenas** [comment]
Frankly @krytarowski, considering how little code is involved, most questions are about design/portability and for the later it would be ideal to hear from someone with access to a broad set of architectures (ex: some NetBSD developer) to see if the currently proposed solution solves the problem or needs more work (ex: to fix alignment issues in SPARC or to enforce pagesize due to some MMU restrictions).

a similar implementation of a pair of external allocation functions to be used in kernel space with a lot of concurrent compiled patterns (say for some firewalling code) and some performance numbers also good to have IMHO.

**Comment by krytarowski** [comment]
> a similar implementation of a pair of external allocation functions to be used in kernel space with a lot of concurrent compiled patterns (say for some firewalling code) and some performance numbers also good to have IMHO.

Do you mean to get something with 2 pointers code + data in the kernel or the mprotect(2) approach with switching the same pointer between RW <-> RX?

**Comment by carenas** [comment]
> > a similar implementation of a pair of external allocation functions to be used in kernel space with a lot of concurrent compiled patterns (say for some firewalling code) and some performance numbers also good to have IMHO.
> 
> Do you mean to get something with 2 pointers code + data in the kernel or the mprotect(2) approach with switching the same pointer between RW <-> RX?

the later; the same approach that was used in that branch or pcre (disable the sljit internal allocator, and provide 2 functions to allocate/free the page that will be allocated and eventually switch permission)

note that for PCRE, since the generated code is not self modifying, mprotect(2) was needed only once, unlike sljit where some tests needed swapping it multiple times; my hope is that bpfjit might be similarly simple.

**Comment by krytarowski** [comment]
Please include invalidation of the cache, similarly to LLVM JIT:

https://github.com/llvm/llvm-project/blob/9f69157bf4a083f539e6759ddd6929c1b3d0bc2a/llvm/lib/Support/Unix/Memory.inc#L187

As far as I guess, there is only one switch RW -> RX in bpfjit.

**Comment by krytarowski** [comment]
> Frankly @krytarowski, considering how little code is involved, most questions are about design/portability and for the later it would be ideal to hear from someone with access to a broad set of architectures (ex: some NetBSD developer) to see if the currently proposed solution solves the problem or needs more work (ex: to fix alignment issues in SPARC or to enforce pagesize due to some MMU restrictions).

mmap() operates on pages (page-sized allocations). It's worth to round it to page size always on the sljit side so it will be easier to reuse in the kernel.

The only part that needs handing as far as I can see is the cache invalidation on enabling RX.

**Comment by krytarowski** [comment]
> note that for PCRE, since the generated code is not self modifying, mprotect(2) was needed only once, unlike sljit where some tests needed swapping it multiple times; my hope is that bpfjit might be similarly simple.

I think that self modifying code should be forbidden in principle.

Multiple switches RW -> RX -> RW -> RX are fine.

**Comment by carenas** [comment]
> Please include invalidation of the cache

sljit already does (as mentioned before) invalidation of the cache, and while the code looks a little suspicious, it seems to work (at least on the systems I have access to); if by any means doesn't work for you, lets fix it, but in a different issue, as that problem would be orthogonal to this one.

**Comment by krytarowski** [comment]
@carenas Can you pull-request this code here?

**Comment by carenas** [comment]
> @carenas Can you pull-request this code here?

pull-request which code?, the one I suggested as easier for testing was the modified PCRE and that patch is to be applied against subversion (or a release package that could be autoreconf/cmake with the right settings) and available from :

  https://bugs.exim.org/attachment.cgi?id=1327&action=diff&context=patch&collapsed=&headers=1&format=raw

**Comment by krytarowski** [comment]
@zherczeg please review.

**Comment by zherczeg** [comment]
I would rather avoid adding an allocator to PCRE. I would add it to sljit instead, and user programs should be able to choose their allocator. I made an experiment with a R^X allocator before, but SELinux does not allow setting X at all except for mapping files (at least I couldn't do) so I stopped working on it. The good thing is that this allocator could be tested even on Linux, and the new macors could be used by the Apple ARM64 port as well.

**Comment by carenas** [comment]
I agree (sorta) in principle, and I definitely agree that PCRE is conceptually NOT the place to add an allocator for sljit, but was the easier place I could think of to build one so we can see how external allocators would work and agree on the design, as well as be able to test the code easily.

now while I also agree that it makes sense to have sljit manage their executable memory internally there a couple of problems with it which mainly W^X has made obvious, and it is that the interface needs fixing as it is leaking.

IMHO, and specially considering the restrictions that SElinux, PaX and other similar constrains are going to push, the right place to "manage" this is in the application (the one that linked with sljit, not an intermediary library like PCRE) and that could make the right decisions based on its own constrains (like PCRE allows through their user provided allocation functions) or by relying in an interface that abstracts the functionality completely (like PCRE tries to do to fallback to interpreter if JIT doesn't work for whatever reason) 

as shown by the proposed changes to sljit in [(/carenas/sljit/tree/nullexec)](/carenas/sljit/tree/nullexec) which tried to use the test as an "external application" (or in the pcre patch) all changes of state should be doable outside of sljit and make sense outside of sljit, since it is the application the one that knows better when it will jump and execute a function, or when it needs to "compile" one (assuming all it got back from the library was a pointer to a function)

**Comment by zherczeg** [comment]
I have created a new W^X allocator: #60
Please check.
