### ISSUE TITLE
Need a function to get the ijump label address

### ISSUE THREAD

**Issue by digitalgust** [zherczeg/sljit#7]
I read the header file that get these two functions

```
SLJIT_API_FUNC_ATTRIBUTE void sljit_set_jump_addr(sljit_uw addr, sljit_uw new_target, sljit_sw executable_offset);
SLJIT_API_FUNC_ATTRIBUTE void sljit_set_const(sljit_uw addr, sljit_sw new_constant, sljit_sw executable_offset);
```

but ,in my situation,  i need the ijump address for lookup switch or table switch.
to get a label address save to my own heap, not the sljit_jump or sljit_const. 

as the code , i need a func to get label address to put in V2PTable.jump_ptr

```
struct V2PTable {
        s32 value; //for value
        s32 bc_pos;//for get jit label addr
        sljit_uw jump_ptr; //for jit jump
    } *table;

//code for save label address
v2p[i].jump_ptr = ...//sljit_get_label_addr(label);

//code for indirect jump
 sljit_emit_ijump(C, SLJIT_JUMP, SLJIT_MEM1(SLJIT_R1), SLJIT_OFFSETOF(struct V2PTable, jump_ptr));

```

**Comment by zherczeg** [comment]
I recommend `SLJIT_FUNC_OFFSET`. The returned value is `sljit_sw` not `sljit_uw` though. You can cast it if you need it.

**Comment by zherczeg** [comment]
I am sorry. You need to use `sljit_get_label_addr` if you want to get the real address of a label. You can use these functions after the code is compiled, but before the compiler is freed.

**Comment by zherczeg** [comment]
https://github.com/zherczeg/sljit/blob/master/test_src/sljitTest.c#L953
You can see its usage here.

**Comment by digitalgust** [comment]
I see the test already , but the label position that would be jump  only can  set to sljit_const or sljit_jump , is there a method to save in my own head as const var

**Comment by zherczeg** [comment]
No, the label address is not restricted to jump/const. You can save it to a memory address / register and jump to this register. I used jump tables using this mechanic. But it seems there is no test for it. I will add one.

**Comment by digitalgust** [comment]
ok,let me try

**Comment by zherczeg** [comment]
https://github.com/zherczeg/sljit/commit/ac9b024f92d529dfe741ba7cc03340f90ae7aafd
I have added tests for jump tables and computed gotos.
