### ISSUE TITLE
push and pop support required 

### ISSUE THREAD

**Issue by digitalgust** [zherczeg/sljit#8]
My JVM jit that based sljit is running success now , but the performance is not large better than C interpreter ,about 150%-300% fast  , because the jvm is based on stack , i need create a stack ,and manage the stack pointer.
```
push_int(struct sljit_compiler *C, sljit_s32 src, sljit_sw srcw) {
    //sp[offset]->ivalue = value
    sljit_emit_op1(C, SLJIT_MOV_S32, SLJIT_MEM1(SLJIT_S0),  SLJIT_OFFSETOF(StackEntry, rvalue), src, srcw);
    sljit_emit_op2(C, SLJIT_ADD, SLJIT_S0, 0, SLJIT_S0, 0, SLJIT_IMM, sizeof(StackEntry) * 1);
}
```

Although the sljit is a stack-less jit tool, and it's really great,  but for stack-based jvm , if there are instruction supported for push and pop , i think the performance would raise, and more register for code use , my jit used a SLJIT_S0 for sp.
Is there possibility for support stack?

**Comment by zherczeg** [comment]
Yes. Please check the following api:
https://github.com/zherczeg/sljit/blob/master/sljit_src/sljitLir.h#L1372

Some projects, such as pcre (a backtracking regex engine) uses this api to manage a stack, which can grow based on needs.

**Comment by zherczeg** [comment]
(Note: the stack is top-down, not bottom-up, because that fits better for cpu instructions)

**Comment by digitalgust** [comment]
but there were not push and pop CPU instructions.

**Comment by zherczeg** [comment]
Pre/post increment/ decrement memory instructions can be used for push/pop. But usually it is better to allocate a larger space with a sub/add instruction, and fill it with memory read/write. Even if you use two instructions for reading/writing memory and update the base register, this can be executed parallelly by and modern superscalar CPU.
