### ISSUE TITLE
vs2017 exec jit execution error 

### ISSUE THREAD

**Issue by digitalgust** [zherczeg/sljit#9]
write privileges , should be the memory for jit code  can't be write , how to solve it .

**Comment by zherczeg** [comment]
I don't use vs2017. If you give more context I might be able to help.

**Comment by digitalgust** [comment]
<img width="1280" alt="截屏2019-12-1416 28 47" src="https://user-images.githubusercontent.com/19265420/70846403-d7eed200-1e93-11ea-8f82-2b7d47a19e47.png">

screen shot

**Comment by digitalgust** [comment]
Now, the jit work on Xcode on mac , gcc on linux, mingw64 on windows, but not vs2017 on windows

**Comment by digitalgust** [comment]
When i run the official test success,  I rechecked my code, I found error that save var jump datatype
"long long" write "long"  ,so the jump pointer error.
