### ISSUE TITLE
How to patch jump or call target on the fly? 

### ISSUE THREAD

**Issue by playXE** [zherczeg/sljit#95]
Statemernt on https://zherczeg.github.io/sljit/ says this: `Target of (conditional) jump and call instructions can be dynamically modified during the execution of the code.`

**Comment by zherczeg** [comment]
Please check: https://github.com/zherczeg/sljit/blob/master/test_src/sljitTest.c#L907

You need to pass SLJIT_REWRITABLE_JUMP, and sljit_set_jump_addr can be used to update the target.

**Comment by playXE** [comment]
@zherczeg thanks for help! I have another question: is `sw` and `uw` types are pointer sized or they are 64 bit sized?

**Comment by zherczeg** [comment]
Pointer. The compiler supports two types for integer computation: 32 bit and pointer (machine word) size.

**Comment by playXE** [comment]
Thanks for help! I guess now I can close this issue :)

**Comment by zherczeg** [comment]
Note: if 64 bit is necessary, you can make a jit which only supports 64 bit machines, and create an interpreter for 32 bit cpus. Even phones have 64 bit cpus these days, you will probably loose nothing with ignoring 32 bit.
