### ISSUE TITLE
Duplicate condition (-Wlogical-op)

### ISSUE THREAD

**Issue by nikic** [zherczeg/sljit#96]
There is a duplicate condition at
https://github.com/zherczeg/sljit/blob/51267551425d68cebcf285d1cd88f8baf6616d86/sljit_src/sljitNativePPC_common.c#L1509 which shows up as a warning under `-Wlogical-op`. Not sure whether one of them should be dropped, or replace with SLJIT_OR/XOR.

**Comment by zherczeg** [comment]
Nice catch! Actually the check is correct, so the second part should be deleted. Do you want to submit a patch or shall I do it?
